### ISSUE TITLE
outbound caller ID : add + or remplace 0 by +

### ISSUE THREAD

**Issue by pierrelauret** [GuillaumeHullin/Grandstream-HT813#3]
Hello,

First, thank you so much for setting everything up.

It has been working very well for a while now.

However, I have an issue, although it doesn't happen all the time...

When I dial a number using speed dial from a VoIP phone (for example, 0600000000), the log in FreePBX registers the number 0600000000, and the syslog shows:

vbnet
Copier le code
Time: Sep 16 08:45:50
Host: HT813
Facility: 
Priority: 
Tag: [c0:74:ad:8e:76:f6] [1.0.17.2] GS_ATA
Message: USER.INFO Call(9)::Call, Creating Call object 9 at port 1:0 with digits 0600000000
However, in the Freebox call register, I see:
![Capture d’écran 2024-09-16 à 09 01 15](https://github.com/user-attachments/assets/ffbf5cb4-dd18-40fb-8468-bd8eeaa18f6f)

Do you have any idea why this might be happening?

Best regards.

**Comment by GuillaumeHullin** [comment]
What about if you dial +33 or 0033 instead of the first zero?
Does your call work?

**Comment by pierrelauret** [comment]
When I dial on the voip phone +33... it does not work
When I dial the voip phone 0033 i see +0033... on the freebox delta side...

**Comment by GuillaumeHullin** [comment]
Ok if you do so via a phone directly on the Freebox? Does it fail also?

**Comment by pierrelauret** [comment]
can not manage to dial the + form my old phone. but when I dial 0033... it remplace it with a 0 and it works.

**Comment by GuillaumeHullin** [comment]
In your first screenshot, does the call work or fail? 
somehow you are facing an issue with the dial plan (I'm guessing FreePBX side). I'm not using anymore the Grandstream, so I can't help you much on that (I switch over to OVH trunk line, cheap and efficient).

**Comment by pierrelauret** [comment]
This is driving me crazy, I can’t figure out where it’s coming from… my dial plan is empty in the trunk and is {x.} in the outbound… I might just start a new config from scratch. I’ll try resetting the HT813 first, and then FreePBX.
Thanks for your answer. Just out of curiosity, are you using the 5-channel trunk on OVH? The one at €9.90?

**Comment by GuillaumeHullin** [comment]
I'm not sure where you got the price of 9.90... but yes I'm using that https://www.ovhtelecom.fr/telephonie/sip-trunk/

**Comment by pierrelauret** [comment]
OK, I change the last setting Channel Dialing of the FXO port to the minimum and it seems to work now.
![Capture d’écran 2024-09-20 à 18 21 53](https://github.com/user-attachments/assets/823fb18e-62e2-4ca8-8c3e-b8557efba192)

**Comment by GuillaumeHullin** [comment]
Congrats on finding the solution :)
